export const ADD_PART = 'ADD_PART';
export const LOAD_MODELS_SUCCESS = 'LOAD_MODELS_SUCCESS';
export const LOAD_PART_CATEGORIES_SUCCESS = 'LOAD_PART_CATEGORIES_SUCCESS';
export const LOAD_PARTS_SUCCESS = 'LOAD_PARTS_SUCCESS';