export const LOAD_MODELS_SUCCESS = 'LOAD_MODELS_SUCCESS';

export const LOAD_PART_CATEGORIES_REQUEST = 'LOAD_PART_CATEGORIES_REQUEST';
export const LOAD_PART_CATEGORIES_SUCCESS = 'LOAD_PART_CATEGORIES_SUCCESS';

export const LOAD_PARTS_FOR_CATEGORY_REQUEST = 'LOAD_PART_FOR_CATEGORY_REQUEST';
export const LOAD_PARTS_FOR_CATEGORY_SUCCESS = 'LOAD_PART_FOR_CATEGORY_SUCCESS';

export const LOAD_PARTS_REQUEST = 'LOAD_PARTS_REQUEST';
export const LOAD_PARTS_SUCCESS = 'LOAD_PARTS_SUCCESS';